import type { Metadata } from "next";
import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import { NextIntlClientProvider } from "next-intl";
import { cookies } from "next/headers";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const vazirmatn= Vazirmatn({
  subsets:["latin"],
  variable: "--font-Vazirmatn",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookieInfo= await cookies();
  const locale = cookieInfo.get("locale")?.value || "fa";
  const isRTL= locale==="fa" ||locale === "pa";
  return (
    <html
      lang={locale}
      dir={locale=== "en"? 'ltr': 'rtl'}

      suppressHydrationWarning
      className={`h-full antialiased ${isRTL ? vazirmatn.variable : inter.variable} `}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NextIntlClientProvider>
        {children}
          </NextIntlClientProvider>
        
        </ThemeProvider>
        </body>
    </html>
  );
}
