import type { Metadata } from "next";
import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const vasirmatn= Vazirmatn({
  subsets:["latin"],
  variable: "--font-Vazirmatn",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full", "antialiased", "font-sans", ${inter.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class">
          <NextIntlClientProvider>

        {children}
          </NextIntlClientProvider>
        
        </ThemeProvider>
        </body>
    </html>
  );
}
